"""Review prompt templates for Claude Code CLI with multi-language support."""

# Severity labels used in review output
SEVERITY_LABELS = {
    "approved": "🟢 LGTM",
    "minor": "🟡 Minor Issues",
    "critical": "🔴 Needs Review"
}

# Turkish prompts
PROMPTS_TR = {
    "review_prompt": """Bu Flutter/Dart pull request'ini kod kalitesi açısından incele.

## PR'daki Commit'ler:
{commit_summary}

## Değişen Dosyalar:
{files_summary}

## Kod Diff:
```diff
{diff_content}
```

## İnceleme Kriterleri:

### 1. Flutter Best Practice'ler
- Widget kompozisyonu doğru mu?
- const constructor'lar kullanılmış mı?
- State management düzgün mü?

### 2. Clean Architecture Uyumu
- Katman ayrımı (domain/data/presentation) doğru mu?
- Dependency injection düzgün uygulanmış mı?
- Repository pattern'e uyulmuş mu?

### 3. Cubit/BLoC Pattern'leri
- State handling doğru mu?
- Event-driven mimari uygulanmış mı?
- State'ler immutable mı?

### 4. Dart Conventions
- Null safety düzgün kullanılmış mı?
- effective_dart kurallarına uyulmuş mu?
- Naming convention'lar doğru mu?

### 5. Performans
- Gereksiz rebuild var mı?
- Memory leak riski var mı?
- Async handling doğru mu?

### 6. Güvenlik
- Input validation yapılmış mı?
- Hassas veri exposure riski var mı?

## Çıktı Formatı:

MUTLAKA aşağıdaki formatta yanıt ver:

### Severity Label
Değişikliklerin genel durumuna göre SADECE BİRİNİ seç:
- 🟢 LGTM - Ciddi sorun yok, kod kalitesi iyi
- 🟡 Minor Issues - Küçük iyileştirmeler önerilir ama kritik değil
- 🔴 Needs Review - Kritik sorunlar var, merge öncesi düzeltilmeli

### Özet
2-3 cümlelik genel değerlendirme.

### Bulgular
Varsa sorunları önem derecesine göre listele:
- **KRİTİK**: Merge öncesi mutlaka düzeltilmeli
- **YÜKSEK**: Düzeltilmesi önerilir
- **ORTA**: İyileştirme önerisi
- **DÜŞÜK**: Stil/convention önerisi

### Dosya Bazlı Öneriler
Varsa spesifik dosya ve satır önerileri.

Yapıcı ve spesifik ol. Gereksiz detaya girme, en önemli konulara odaklan.""",

    "comment_header": "## 🤖 Otomatik Kod İncelemesi",
    "comment_footer": "*Bu inceleme Claude Code CLI tarafından otomatik oluşturulmuştur. Önerileri değerlendirirken kendi muhakemenizi kullanın.*"
}

# English prompts
PROMPTS_EN = {
    "review_prompt": """Review this Flutter/Dart pull request for code quality.

## Commits in PR:
{commit_summary}

## Changed Files:
{files_summary}

## Code Diff:
```diff
{diff_content}
```

## Review Criteria:

### 1. Flutter Best Practices
- Is widget composition correct?
- Are const constructors used?
- Is state management proper?

### 2. Clean Architecture Compliance
- Is layer separation (domain/data/presentation) correct?
- Is dependency injection properly implemented?
- Is repository pattern followed?

### 3. Cubit/BLoC Patterns
- Is state handling correct?
- Is event-driven architecture applied?
- Are states immutable?

### 4. Dart Conventions
- Is null safety properly used?
- Are effective_dart rules followed?
- Are naming conventions correct?

### 5. Performance
- Are there unnecessary rebuilds?
- Is there memory leak risk?
- Is async handling correct?

### 6. Security
- Is input validation done?
- Is there sensitive data exposure risk?

## Output Format:

You MUST respond in the following format:

### Severity Label
Based on overall changes, select ONLY ONE:
- 🟢 LGTM - No serious issues, code quality is good
- 🟡 Minor Issues - Small improvements suggested but not critical
- 🔴 Needs Review - Critical issues found, must fix before merge

### Summary
2-3 sentence overall assessment.

### Findings
List issues by severity if any:
- **CRITICAL**: Must fix before merge
- **HIGH**: Should fix
- **MEDIUM**: Improvement suggestion
- **LOW**: Style/convention suggestion

### File-Specific Suggestions
Specific file and line suggestions if any.

Be constructive and specific. Avoid unnecessary details, focus on the most important issues.""",

    "comment_header": "## 🤖 Automatic Code Review",
    "comment_footer": "*This review was automatically generated by Claude Code CLI. Use your own judgment when evaluating suggestions.*"
}

# Language mapping
PROMPTS = {
    "tr": PROMPTS_TR,
    "en": PROMPTS_EN
}


def get_review_prompt(
    commit_summary: str,
    files_summary: str,
    diff_content: str,
    language: str = "tr"
) -> str:
    """
    Generate the review prompt for Flutter/Dart code.

    Args:
        commit_summary: Summary of commits in the PR
        files_summary: Summary of file changes
        diff_content: Raw diff content
        language: Language code (tr/en)

    Returns:
        Complete prompt string for Claude
    """
    prompts = PROMPTS.get(language, PROMPTS_TR)

    return prompts["review_prompt"].format(
        commit_summary=commit_summary,
        files_summary=files_summary,
        diff_content=diff_content
    )


def get_comment_header(language: str = "tr") -> str:
    """Get localized comment header."""
    prompts = PROMPTS.get(language, PROMPTS_TR)
    return prompts["comment_header"]


def get_comment_footer(language: str = "tr") -> str:
    """Get localized comment footer."""
    prompts = PROMPTS.get(language, PROMPTS_TR)
    return prompts["comment_footer"]
